apiVersion: v1
kind: Pod
metadata:
  name: bogo-manual
spec:
  containers:
  - name: bogo
    image: dockerbogo/bogo
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
        protocol: TCP
