apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: testingpod
  name: testingpod
spec:
  nodeSelector:
     hw: max
  containers:
  - image: nginx
    name: testingpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
