apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ssd-monitor
  labels:
    app: ssd-monitor
spec:
  selector:
    matchLabels:
      app: ssd-monitor
  template:
    metadata:
      labels:
        app: ssd-monitor
    spec:
      containers:
      - name: main
        image: dockerbogo/ssd-monitor